### ISSUE TITLE
classnames could not be found within the project or in these directories:

### ISSUE THREAD

**Issue by wuzhijianMr** [ant-design/ant-design-mobile-rn#1245] opened 2022-07-26 02:22 UTC

**Comment by wuzhijianMr** [comment] 2022-07-26 02:23
error Unable to resolve module classnames from F:\react\fyt\node_modules\@ant-design\react-native\lib\tag\index.js: classnames could not be found within the project or in these directories:
  node_modules\@ant-design\react-native\node_modules
  node_modules

**Comment by 1uokun** [comment] 2022-07-26 15:02
Duplicate of #1229

**Closed by 1uokun** 2022-07-26 15:02 UTC
