### ISSUE TITLE
Modal.alert有几率会出现抖动现象（Modal.alert is rembled）

### ISSUE THREAD

**Issue by ljh257110** [ant-design/ant-design-mobile-rn#1192] opened 2021-08-11 01:36 UTC
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://bat100-dev.oss-cn-qingdao.aliyuncs.com/file/f290934d69cd.mp4](https://bat100-dev.oss-cn-qingdao.aliyuncs.com/file/f290934d69cd.mp4)

### Steps to reproduce
Modal.alert('货到付款提醒', '货到付款订单，采购商收货后在线付款或开具电子承兑汇票，请确认后接单', [
            {
                text: '返回',
                onPress: () => { },
                style: 'cancel',
            },
            {
                text: '确认接单',
                onPress: () => confirmOrderFun(item, props)
             }
 ]);

### What is expected?
normally appear （modal正常显示）

### What is actually happening?
modal is rembled（modal会出现抖动现象，应该说几率非常小，但不知是什么原因）

| Environment | Info |
|---|---|
| antd | 3.2.2 |
| React | 0.63.2 |
| System | ios or xiaomi8 |
| Browser | app |

**Comment by 1uokun** [comment] 2021-08-11 04:02
Duplicate of https://github.com/ant-design/ant-design-mobile-rn/issues/1095

**Closed by 1uokun** 2021-08-11 04:02 UTC
Labels: Duplicate
