### ISSUE TITLE
InputItem清除icon丢失？

### ISSUE THREAD

**Issue by Fled8617** [ant-design/ant-design-mobile-rn#227] opened 2018-12-26 11:39 UTC
- [x] I have searched the [issues](https://github.com/ant-design/ant-design-mobile-rn/issues) of this repository and believe that this is not a duplicate.

### Version
3.0.1

### Environment
安卓

### Reproduction link
[http://手机扫码演示，web暂时看不到](http://手机扫码演示，web暂时看不到)

### Steps to reproduce
<InputItem clear/>

### What is expected?
正常显示X号

### What is actually happening?
看不到X号

**Comment by jskod** [comment] 2018-12-29 07:02
After upgrading to 3x, <InputItem /> with `clear` prop, shows only a gray round icon on right of the input to clear the input. But it doesn't show `x` or cross icon. When I tap on the icon, then it changes color and `x` or cross icon shows up. Otherwise, it only shows a circular icon.....

**Comment by jskod** [comment] 2018-12-29 07:03
```
<InputItem
      clear
       value={buyBoxAmount}
        onChange={this.handleListPriceChange}
        onBlur={this.getFeeEstimate}
         placeholder="0.00"
         labelNumber={7}
          >
            List Price ($)
          </InputItem>
```

**Comment by JadeTao** [comment] 2019-01-02 13:06
I have reproduced this issue only in Android not in iOS. This is not because icon is lost but because the `TouchableOpacity` has an improper background color.
Maybe I can fix it.

**Comment by bang88** [comment] 2019-01-03 08:10
fixed by @JadeTao

**Closed by bang88** 2019-01-03 08:10 UTC
Labels: Need Reproduce

**Comment by M45ter** [comment] 2019-04-24 06:34
@bang88 
今天试了下InputItem，clear的图标没有显示，官网的演示也没有显示
Version
3.1.5

Environment
安卓

React native version
0.59.5
