### ISSUE TITLE
文档代码演示报错

### ISSUE THREAD

**Issue by chaos-zhu** [ant-design/ant-design-mobile-rn#1232] opened 2022-04-28 05:47 UTC
### Reproduction link

[https://rn.mobile.ant.design/components/toast-cn/](https://rn.mobile.ant.design/components/toast-cn/)

### Steps to reproduce

所有组件无法预览

### What is expected?

正常预览

### What is actually happening?

正常预览

| Environment | Info |
| --- | --- |
| antd | 5.0.0 |
| React | 0.68 |
| System | win10 |
| Browser | chrome |

![image](https://user-images.githubusercontent.com/44160914/165685327-70f61922-2fab-4e58-a9aa-38c407d1f652.png)

**Comment by 1uokun** [comment] 2022-04-29 11:09
Duplicate of #1227

**Closed by 1uokun** 2022-04-29 11:09 UTC
